name: Fetch Tech News

on:
  schedule:
    - cron: '0 12 * * *'   # daily 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch news headlines
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: python -m src.fetch

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/raw/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add news data $(date -u +%Y-%m-%dT%H:%M:%SZ) [skip ci]"
          # захист від гонок: оновимо локальну гілку перед пушем
          git pull --rebase || true
          for i in 1 2 3; do git push && exit 0 || (echo "Retry $i..." && sleep 2); done
          # якщо після 3 спроб не вийшло — нехай фейлиться
          git push
        fi
