name: Fetch Tech News

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Fetch news headlines
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        python -m src.fetch
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/raw/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add news data $(date -u +%Y-%m-%d)"
          git push
        fi